### ISSUE TITLE
Moderninzing import/export - Avoid dynamic require

### ISSUE THREAD

**Issue by aminya** [file-icons/fs#7]
I tried to build atom plugin using webpack, however because of the way the internal parts of this package call other functions (dynamic require), it fails to bundle.
Probably by using modern import/export the actual package will become faster too.

**Comment by Alhadis** [comment]
Atom doesn't support native ESM modules. Also, I intend to deprecate this module in future In favour of a different solution.

> Probably by using modern import/export the actual package will become faster too.

<img src="https://user-images.githubusercontent.com/2346707/78249434-0f17ea80-753a-11ea-8e08-07947711f635.jpg" width="450" />

**Comment by aminya** [comment]
> 
> 
> Atom doesn't support native ESM modules. 
> > Probably by using modern import/export the actual package will become faster too.
> 
> <img alt="" width="450" src="https://user-images.githubusercontent.com/2346707/78249434-0f17ea80-753a-11ea-8e08-07947711f635.jpg">

There a tons of transpilers and bundlers that already solved this issue.

**Comment by Alhadis** [comment]
> There a tons of transpilers and bundlers that already solved this issue.

You... *do* know said tools transpile ESM to `require()` calls anyway, right...? It'd be equally slow as just using an ordinary `require()` statement, if not slower.

**Comment by aminya** [comment]
Bundlers merge the files together and tree shakes the dependencies, so all of that goes away, making the code faster. When you use `require`, you remove that option. Your choice.
https://engineering.universe.com/improving-browser-performance-10x-f9551927dcff

**Comment by Alhadis** [comment]
Once again, **the performance differences are negligible**. Please stop proposing micro-optimisations. Look, I get it. The package could be faster. A lot of that is to do with synchronous filesystem calls, which are difficult to remove without rewriting everything from scratch. *That* is where the performance drain is. Not the on-disk representation of package code which might offer a couple of microseconds' difference *at best*.

**Comment by aminya** [comment]
> Please stop proposing micro-optimisations. 

10X speed-up:
https://github.com/JunoLab/atom-indent-detective/pull/17

**Comment by Alhadis** [comment]
> 10X speed-up:

For a codebase that was written in CoffeeScript? Not surprised.

**Comment by aminya** [comment]
> For a codebase that was written in CoffeeScript? Not surprised.

I am not surprised that you are not surprised. Calling optimization "micro-optimization", calling delaying execution using async "optimization" doesn't remain any common ground.

**Comment by Alhadis** [comment]
Okay, listen. Clearly, you don't have a very good understanding of how Atom works. When Atom loads a package containing a transpiled language, it transpiles it *at startup*, using locally-cached results if possible (but this still adds overhead because it has to check the package's files to see if its cache is out-of-date). The reason JunoLab/atom-indent-detective#17 has an ostensible improvement to startup time is because you're compiling it *ahead of time*. If you took the same TypeScript code and left it to Atom to transpile at startup, there wouldn't be much of a difference.

> calling delaying execution using async "optimization" doesn't remain any common ground.

Do you even know why sync I/O is bad? Let me explain. Your system has only a finite amount of resources to allocate each process. When said allocation runs low, disk I/O becomes slower because it's sucking through a straw, so to speak. When a synchronous filesystem op runs, the *entire process* is stalled until it completes. Even when there are plenty of resources to burn, blocking the main thread at startup still isn't a very good idea. This is what you're seeing.
